serviceName: vector_sphere
nodeType: 0
timeOut: 30
defaultPort: 8080
heartbeat: 10
etcd:
  endpoints:
  - ip: "localhost"
    port: 2379
    isMaster: true
schedulerWorkerCount: 10
httpPort: 8090
taskTimeout: 60
healthCheckInterval: 30
dataDir: ./data