apiVersion: v1
kind: ConfigMap
metadata:
  name: vectorsphere-config
  namespace: vectorsphere
data:
  global.conf: |
    [system]
    log_level = "info"
    max_connections = 1000
    
    [etcd]
    endpoints = "etcd-service:2379"
    
    [redis]
    addr = "redis-service:6379"
    
    [vector]
    dimension = 768
    index_type = "hnsw"
    
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'vectorsphere'
        static_configs:
          - targets: ['master-service:8080', 'worker-service:8081', 'vectordb-service:8082']